PROGRAM What(INPUT, OUTPUT);
VAR 
  Ch: CHAR;
BEGIN
  WRITELN('INPUT DATA:'); 
  READ(Ch);
  IF '0' <= Ch 
  THEN 
    IF Ch <= '9' 
    THEN 
      WRITELN('YES, YOUR SYMBOL IS NUMBER')
    ELSE 
      WRITELN('NO, YOUR SYMBOL IS LETTER')
  ELSE 
    WRITELN('NO, YOUR SYMBOL IS LETTER')
END.